services:
  - type: web
    name: kaya-forgery-detection
    env: python
    pythonVersion: "3.11.9"
    region: oregon
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    autoDeploy: true

